In [2]:
# ## contains instituitons in US with info on location, level and classification

import subprocess
import sqlite3 as sqlite
import argparse
import os
import pandas as pd
import numpy as np 

# os.chdir("../../")
# print(os.getcwd()) 
#os.chdir("/home/mona/mag_sample/")

from src.dataprep.helpers.functions import *
from src.dataprep.helpers.variables import *

In [6]:
# ## Read file
print("Reading file... \n")
datapath="./data/cng_institutions/"

cng_institutions=pd.read_excel(datapath+"CCIHE2021-PublicData.xlsx", sheet_name="Data",
                        usecols = ["unitid", "name", "city", "stabbr", "iclevel", "basic2021"],
                        header=0)


# print(cng_institutions)


# ## Clean file: drop if unclassified institution: none
print("Cleaning... \n")
print("No institutions unspecified")

cng_institutions=cng_institutions.rename(columns={"name": "originalname"})
cng_institutions=cng_institutions.loc[cng_institutions["iclevel"] ==1]
cng_institutions = cng_institutions.drop(columns = ["iclevel"])
cng_institutions["normalizedname"] = normalize_string(cng_institutions["originalname"], replace_hyphen = " ")

Reading file...

Cleaning...

No institutions unspecified

,unitid,originalname,city,stabbr,basic2021,normalizedname
0,177834,A T Still University of Health Sciences,Kirksville,MO,25,a t still university of health sciences
1,134811,AI Miami International University of Art and D...,Miami,FL,22,ai miami international university of art and d...
2,429094,AOMA Graduate School of Integrative Medicine,Austin,TX,26,aoma graduate school of integrative medicine
3,404994,ASA College,Brooklyn,NY,14,asa college
8,180203,Aaniiih Nakoda College,Harlem,MT,33,aaniiih nakoda college

In [7]:
cng_institutions.head()

,unitid,originalname,city,stabbr,basic2021,normalizedname
0,177834,A T Still University of Health Sciences,Kirksville,MO,25,a t still university of health sciences
1,134811,AI Miami International University of Art and D...,Miami,FL,22,ai miami international university of art and d...
2,429094,AOMA Graduate School of Integrative Medicine,Austin,TX,26,aoma graduate school of integrative medicine
3,404994,ASA College,Brooklyn,NY,14,asa college
8,180203,Aaniiih Nakoda College,Harlem,MT,33,aaniiih nakoda college
...,...,...,...,...,...,...
3930,181853,York College,York,NE,22,york college
3931,217059,York College of Pennsylvania,York,PA,20,york college of pennsylvania
3935,141361,Young Harris College,Young Harris,GA,21,young harris college
3936,206695,Youngstown State University,Youngstown,OH,18,youngstown state university
3938,204255,Zane State College,Zanesville,OH,6,zane state college

In [8]:
con=sqlite.connect(db_file)

with con: 
    cng_institutions.to_sql("cng_institutions",con=con, if_exists="replace", index=False, chunksize=cng_institutions.shape[0])

In [12]:
## TODO: add index 

# ## Analyze and finish 
analyze_db(con)

Running ANALYZE...

ProgrammingError: Cannot operate on a closed database.

In [10]:
# ## Check institutions and names
query="select AffiliationId, NormalizedName, Latitude, Longitude from affiliations where iso3166code = 'US'"
mag=pd.read_sql(sql=query, con=con)
mag.head()

,AffiliationId,NormalizedName,Latitude,Longitude
0,50614327,amec foster wheeler,41.880707,-87.67417
1,80046288,walden university,44.981327,-93.26623
2,94975175,des moines university,41.584000,-93.66200
3,158506100,pennsylvania board of probation and parole,40.259860,-76.88223
4,192633058,university of saint joseph,41.779600,-72.73050

In [11]:

con.close()

print("Done.")

Done.